// Mock data for testing the platform

export const mockAgents = [
  {
    id: 'agent-1',
    name: 'Support Client Pro',
    description: 'Agent spécialisé dans le support client 24/7 avec analyse de sentiment',
    category: 'Support',
    status: 'active',
    model: 'gpt-4',
    temperature: 0.7,
    systemPrompt: 'Tu es un assistant de support client professionnel et empathique. Analyse le sentiment et réponds avec courtoisie.',
    usageCount: 1247,
    lastUsed: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
    organizationId: 'org-1',
    directionId: 'dir-2',
    departementId: 'dept-2-1',
    shared: false,
    owner: 'user-business', // Owner can modify and share
    tags: ['support', 'client', 'sentiment'],
    icon: '💬',
    color: 'blue',
    // Performance metrics
    avgResponseTime: 2.3,
    successRate: 94.5,
    satisfactionScore: 4.6,
    // Activity history
    recentActivities: [
      { date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), user: 'Marie Dubois', action: 'Exécution', duration: 2.1, status: 'success' },
      { date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), user: 'Pierre Martin', action: 'Exécution', duration: 2.5, status: 'success' },
      { date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(), user: 'Sophie Bernard', action: 'Exécution', duration: 1.9, status: 'success' },
      { date: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), user: 'Marc Petit', action: 'Exécution', duration: 3.2, status: 'error' },
      { date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), user: 'Julie Roux', action: 'Exécution', duration: 2.0, status: 'success' },
    ],
    // Usage history (last 7 days)
    usageHistory: [
      { date: '2024-12-02', count: 45, avgDuration: 2.3 },
      { date: '2024-12-01', count: 52, avgDuration: 2.1 },
      { date: '2024-11-30', count: 38, avgDuration: 2.5 },
      { date: '2024-11-29', count: 41, avgDuration: 2.2 },
      { date: '2024-11-28', count: 48, avgDuration: 2.4 },
      { date: '2024-11-27', count: 35, avgDuration: 2.0 },
      { date: '2024-11-26', count: 42, avgDuration: 2.3 },
    ]
  },
  {
    id: 'agent-2',
    name: 'Analyseur de Documents',
    description: 'Extraction et analyse de documents PDF, Word, Excel avec résumés intelligents',
    category: 'Analyse',
    status: 'active',
    model: 'claude-3',
    temperature: 0.3,
    systemPrompt: 'Tu es un expert en analyse documentaire. Extrais les informations clés et fournis des résumés structurés.',
    usageCount: 834,
    lastUsed: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    directionId: 'dir-2',
    departementId: 'dept-2-2',
    shared: true,
    tags: ['documents', 'analyse', 'extraction'],
    icon: '📄',
    color: 'green'
  },
  {
    id: 'agent-3',
    name: 'Générateur de Code',
    description: 'Assistant de développement pour générer du code propre et documenté',
    category: 'Développement',
    status: 'active',
    model: 'gpt-4',
    temperature: 0.2,
    systemPrompt: 'Tu es un développeur expert. Génère du code propre, optimisé et bien documenté.',
    usageCount: 2103,
    lastUsed: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    directionId: 'dir-3',
    departementId: 'dept-3-1',
    shared: false,
    tags: ['code', 'développement', 'programmation'],
    icon: '💻',
    color: 'purple'
  },
  {
    id: 'agent-4',
    name: 'Assistant Marketing',
    description: 'Création de contenu marketing, posts réseaux sociaux, newsletters',
    category: 'Marketing',
    status: 'active',
    model: 'gpt-3.5',
    temperature: 0.9,
    systemPrompt: 'Tu es un expert marketing créatif. Génère du contenu engageant et optimisé pour les conversions.',
    usageCount: 567,
    lastUsed: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    directionId: 'dir-2',
    departementId: 'dept-2-2',
    shared: false,
    tags: ['marketing', 'contenu', 'social'],
    icon: '📱',
    color: 'orange'
  },
  {
    id: 'agent-5',
    name: 'Analyste Financier',
    description: 'Analyse de données financières, prévisions et recommandations',
    category: 'Finance',
    status: 'active',
    model: 'gpt-4',
    temperature: 0.1,
    systemPrompt: 'Tu es un analyste financier expert. Analyse les données et fournis des insights précis.',
    usageCount: 445,
    lastUsed: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    directionId: 'dir-6',
    departementId: 'dept-6-2',
    shared: true,
    tags: ['finance', 'analyse', 'prévisions'],
    icon: '💰',
    color: 'emerald'
  },
  {
    id: 'agent-6',
    name: 'Coach RH',
    description: 'Assistant RH pour recrutement, entretiens et évaluations',
    category: 'RH',
    status: 'active',
    model: 'gemini-pro',
    temperature: 0.6,
    systemPrompt: 'Tu es un expert RH bienveillant. Aide au recrutement et à la gestion des talents.',
    usageCount: 312,
    lastUsed: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), // 6 hours ago
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    directionId: 'dir-5',
    departementId: 'dept-5-1',
    shared: true,
    tags: ['RH', 'recrutement', 'talents'],
    icon: '👥',
    color: 'pink'
  },
]

export const mockWorkflows = [
  {
    id: 'workflow-1',
    name: 'Traitement Automatique des Tickets',
    description: 'Réception → Analyse → Priorisation → Routage automatique vers le bon service',
    category: 'Support',
    status: 'active',
    steps: 5,
    executionCount: 3421,
    lastExecuted: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 minutes ago
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    directionId: 'dir-2',
    departementId: 'dept-2-1',
    shared: false,
    avgExecutionTime: 4.2,
    successRate: 98.5,
    icon: '🎫',
    color: 'blue',
    nodes: [
      { id: 'n1', type: 'trigger', label: 'Nouveau ticket' },
      { id: 'n2', type: 'agent', label: 'Analyse sentiment' },
      { id: 'n3', type: 'condition', label: 'Priorité?' },
      { id: 'n4', type: 'action', label: 'Routage équipe' },
      { id: 'n5', type: 'notification', label: 'Notification client' },
    ]
  },
  {
    id: 'workflow-2',
    name: 'Analyse Quotidienne des Ventes',
    description: 'Collecte données → Analyse tendances → Génération rapport → Envoi équipe',
    category: 'Ventes',
    status: 'active',
    steps: 4,
    executionCount: 156,
    lastExecuted: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(), // 12 hours ago
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    directionId: 'dir-2',
    departementId: 'dept-2-1',
    shared: true,
    avgExecutionTime: 8.7,
    successRate: 100,
    icon: '📊',
    color: 'green',
    nodes: [
      { id: 'n1', type: 'schedule', label: 'Tous les jours 8h' },
      { id: 'n2', type: 'agent', label: 'Analyse des ventes' },
      { id: 'n3', type: 'agent', label: 'Génération rapport' },
      { id: 'n4', type: 'action', label: 'Envoi par email' },
    ]
  },
  {
    id: 'workflow-3',
    name: 'Onboarding Nouveaux Employés',
    description: 'Envoi bienvenue → Création comptes → Formation → Suivi progression',
    category: 'RH',
    status: 'active',
    steps: 6,
    executionCount: 87,
    lastExecuted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-1',
    directionId: 'dir-5',
    departementId: 'dept-5-1',
    shared: true,
    avgExecutionTime: 15.3,
    successRate: 95.4,
    icon: '🎓',
    color: 'purple',
    nodes: [
      { id: 'n1', type: 'trigger', label: 'Nouvel employé' },
      { id: 'n2', type: 'action', label: 'Email de bienvenue' },
      { id: 'n3', type: 'action', label: 'Création comptes' },
      { id: 'n4', type: 'agent', label: 'Plan de formation' },
      { id: 'n5', type: 'schedule', label: 'Suivi hebdomadaire' },
      { id: 'n6', type: 'notification', label: 'Rapport RH' },
    ]
  },
  {
    id: 'workflow-4',
    name: 'Génération Contenu Social Media',
    description: 'Veille tendances → Génération posts → Planification → Publication auto',
    category: 'Marketing',
    status: 'active',
    steps: 4,
    executionCount: 234,
    lastExecuted: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    directionId: 'dir-2',
    departementId: 'dept-2-2',
    shared: false,
    avgExecutionTime: 3.8,
    successRate: 97.2,
    icon: '📱',
    color: 'orange',
    nodes: [
      { id: 'n1', type: 'schedule', label: 'Quotidien 9h' },
      { id: 'n2', type: 'agent', label: 'Veille tendances' },
      { id: 'n3', type: 'agent', label: 'Génération posts' },
      { id: 'n4', type: 'action', label: 'Publication' },
    ]
  },
  {
    id: 'workflow-5',
    name: 'Alerte Anomalies Financières',
    description: 'Monitoring transactions → Détection anomalies → Alerte équipe → Analyse',
    category: 'Finance',
    status: 'active',
    steps: 5,
    executionCount: 12456,
    lastExecuted: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 minutes ago
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    organizationId: 'org-2',
    directionId: 'dir-6',
    departementId: 'dept-6-2',
    shared: true,
    avgExecutionTime: 1.2,
    successRate: 99.8,
    icon: '🚨',
    color: 'red',
    nodes: [
      { id: 'n1', type: 'trigger', label: 'Monitoring continu' },
      { id: 'n2', type: 'agent', label: 'Détection anomalie' },
      { id: 'n3', type: 'condition', label: 'Seuil dépassé?' },
      { id: 'n4', type: 'notification', label: 'Alerte urgente' },
      { id: 'n5', type: 'agent', label: 'Rapport détaillé' },
    ]
  },
]

export const mockMarketplaceAgents = [
  {
    id: 'market-1',
    name: 'ChatBot Multilingue Pro',
    description: 'Agent conversationnel avancé supportant 50+ langues avec détection automatique',
    category: 'Communication',
    price: 'Gratuit',
    rating: 4.8,
    reviews: 234,
    downloads: 5420,
    publisher: 'Hexagone AI',
    verified: true,
    icon: '🌍',
    tags: ['chatbot', 'multilingue', 'support'],
    capabilities: ['50+ langues', 'Détection auto', 'Sentiment', 'Historique'],
  },
  {
    id: 'market-2',
    name: 'Assistant Juridique',
    description: 'Analyse de contrats, conformité RGPD, conseils juridiques personnalisés',
    category: 'Juridique',
    price: '49€/mois',
    rating: 4.9,
    reviews: 156,
    downloads: 2340,
    publisher: 'LegalTech AI',
    verified: true,
    icon: '⚖️',
    tags: ['juridique', 'contrats', 'RGPD'],
    capabilities: ['Analyse contrats', 'RGPD', 'Conformité', 'Conseils'],
  },
  {
    id: 'market-3',
    name: 'Détecteur de Fraude',
    description: 'Machine Learning avancé pour détecter les fraudes en temps réel',
    category: 'Sécurité',
    price: '99€/mois',
    rating: 4.7,
    reviews: 89,
    downloads: 1230,
    publisher: 'SecureAI',
    verified: true,
    icon: '🛡️',
    tags: ['sécurité', 'fraude', 'ML'],
    capabilities: ['Temps réel', 'ML avancé', 'Alertes', 'Reporting'],
  },
  {
    id: 'market-4',
    name: 'Créateur de Présentations',
    description: 'Génération automatique de slides professionnelles à partir de texte',
    category: 'Productivité',
    price: 'Gratuit',
    rating: 4.6,
    reviews: 445,
    downloads: 8920,
    publisher: 'DesignAI',
    verified: false,
    icon: '📊',
    tags: ['présentation', 'design', 'auto'],
    capabilities: ['Auto-design', 'Templates', 'Export PPT', 'Branding'],
  },
  {
    id: 'market-5',
    name: 'Optimiseur SEO',
    description: 'Analyse et optimisation SEO de contenu web avec recommandations',
    category: 'Marketing',
    price: '29€/mois',
    rating: 4.5,
    reviews: 312,
    downloads: 4560,
    publisher: 'GrowthAI',
    verified: true,
    icon: '🚀',
    tags: ['SEO', 'marketing', 'web'],
    capabilities: ['Analyse SEO', 'Mots-clés', 'Backlinks', 'Audit'],
  },
  {
    id: 'market-6',
    name: 'Assistant Médical',
    description: 'Aide au diagnostic, analyse de symptômes, recommandations médicales',
    category: 'Santé',
    price: '149€/mois',
    rating: 4.9,
    reviews: 67,
    downloads: 890,
    publisher: 'HealthAI Pro',
    verified: true,
    icon: '🏥',
    tags: ['santé', 'médical', 'diagnostic'],
    capabilities: ['Diagnostic', 'Symptômes', 'Base de données', 'Certifié'],
  },
  {
    id: 'market-7',
    name: 'Traducteur Technique',
    description: 'Traduction spécialisée de documents techniques et scientifiques',
    category: 'Traduction',
    price: '39€/mois',
    rating: 4.7,
    reviews: 178,
    downloads: 3210,
    publisher: 'TranslateAI',
    verified: true,
    icon: '🔤',
    tags: ['traduction', 'technique', 'documents'],
    capabilities: ['Multi-langues', 'Technique', 'Contexte', 'Glossaire'],
  },
  {
    id: 'market-8',
    name: 'Assistant E-commerce',
    description: 'Recommandations produits, analyse comportement, optimisation conversions',
    category: 'E-commerce',
    price: '79€/mois',
    rating: 4.8,
    reviews: 290,
    downloads: 6540,
    publisher: 'ShopAI',
    verified: true,
    icon: '🛒',
    tags: ['e-commerce', 'ventes', 'recommandations'],
    capabilities: ['Recommandations', 'Analytics', 'A/B Testing', 'Intégrations'],
  },
]

export const mockMarketplaceWorkflows = [
  {
    id: 'market-w1',
    name: 'Pipeline Recrutement Automatisé',
    description: 'Collecte CV → Screening IA → Planification entretiens → Suivi candidats',
    category: 'RH',
    price: 'Gratuit',
    rating: 4.7,
    reviews: 123,
    downloads: 2340,
    publisher: 'HRTech Solutions',
    verified: true,
    icon: '👔',
    tags: ['recrutement', 'RH', 'automatisation'],
    steps: 8,
  },
  {
    id: 'market-w2',
    name: 'Gestion Complète des Factures',
    description: 'Réception → Extraction données → Validation → Comptabilisation → Paiement',
    category: 'Finance',
    price: '59€/mois',
    rating: 4.9,
    reviews: 89,
    downloads: 1560,
    publisher: 'FinanceAI',
    verified: true,
    icon: '💳',
    tags: ['factures', 'finance', 'comptabilité'],
    steps: 6,
  },
  {
    id: 'market-w3',
    name: 'Campagne Email Marketing',
    description: 'Segmentation → Personnalisation → Envoi → Suivi → Optimisation',
    category: 'Marketing',
    price: '39€/mois',
    rating: 4.6,
    reviews: 267,
    downloads: 4230,
    publisher: 'MarketingPro',
    verified: true,
    icon: '📧',
    tags: ['email', 'marketing', 'campagne'],
    steps: 7,
  },
]

export const mockDirections = [
  {
    id: 'dir-1',
    name: 'Direction Générale',
    description: 'Pilotage stratégique et gouvernance de l\'organisation',
    icon: '🏢',
    color: 'purple',
    departements: [
      { id: 'dept-1-1', name: 'Département Direction', userCount: 5, agentCount: 3 },
      { id: 'dept-1-2', name: 'Département Stratégie', userCount: 8, agentCount: 5 },
    ]
  },
  {
    id: 'dir-2',
    name: 'Direction Commerciale',
    description: 'Développement commercial et relation clients',
    icon: '💼',
    color: 'blue',
    departements: [
      { id: 'dept-2-1', name: 'Département Ventes', userCount: 25, agentCount: 12 },
      { id: 'dept-2-2', name: 'Département Marketing', userCount: 15, agentCount: 8 },
      { id: 'dept-2-3', name: 'Département Partenariats', userCount: 10, agentCount: 4 },
    ]
  },
  {
    id: 'dir-3',
    name: 'Direction Technique',
    description: 'Développement produit et infrastructure IT',
    icon: '💻',
    color: 'green',
    departements: [
      { id: 'dept-3-1', name: 'Département Développement', userCount: 35, agentCount: 20 },
      { id: 'dept-3-2', name: 'Département Infrastructure', userCount: 18, agentCount: 15 },
      { id: 'dept-3-3', name: 'Département Support', userCount: 22, agentCount: 10 },
    ]
  },
  {
    id: 'dir-4',
    name: 'Direction des Opérations',
    description: 'Gestion opérationnelle et chaîne de valeur',
    icon: '⚙️',
    color: 'orange',
    departements: [
      { id: 'dept-4-1', name: 'Département Production', userCount: 40, agentCount: 18 },
      { id: 'dept-4-2', name: 'Département Logistique', userCount: 28, agentCount: 12 },
      { id: 'dept-4-3', name: 'Département Qualité', userCount: 12, agentCount: 7 },
    ]
  },
  {
    id: 'dir-5',
    name: 'Direction des Ressources Humaines',
    description: 'Gestion des talents et développement RH',
    icon: '👥',
    color: 'pink',
    departements: [
      { id: 'dept-5-1', name: 'Département Recrutement', userCount: 10, agentCount: 6 },
      { id: 'dept-5-2', name: 'Département Formation', userCount: 8, agentCount: 5 },
      { id: 'dept-5-3', name: 'Département Paie', userCount: 6, agentCount: 4 },
    ]
  },
  {
    id: 'dir-6',
    name: 'Direction Financière',
    description: 'Gestion financière et comptabilité',
    icon: '💰',
    color: 'emerald',
    departements: [
      { id: 'dept-6-1', name: 'Département Comptabilité', userCount: 15, agentCount: 8 },
      { id: 'dept-6-2', name: 'Département Contrôle de Gestion', userCount: 12, agentCount: 10 },
      { id: 'dept-6-3', name: 'Département Trésorerie', userCount: 7, agentCount: 5 },
    ]
  },
]